export const generateNames = () => {
  const firstName = [
    "White",
    "Blue",
    "Red",
    "Aqua",
    "Silver",
    "Orange",
    "Lime",
    "Brown",
    "Violet",
    "Gray",
    "Black",
    "Purple",
    "Gold",
    "Green",
    "Pink",
    "Ultramarine",
    "Indigo",
    "Burlywood",
    "Vermilion",
    "Amaranth",
    "Skobeloff",
    "Feldgrau",
    "Phlox",
    "Viridian",
    "Glaucous",
    "Zaffre",
  ];
  const secondName = [
    "Hornet",
    "Pony",
    "Anaconda",
    "Ocelot",
    "Pelican",
    "Panda",
    "Chinchilla",
    "Snipe",
    "Monkey",
    "Catfish",
    "Thrush",
    "Vulture",
    "Stingray",
    "Rabbit",
    "Chipmunk",
    "Mule",
    "Piranha",
    "Parrot",
    "Hamster",
    "Ostrich",
    "Cardinal",
    "Grouse",
    "Mouse",
    "Minnow",
    "Kingfisher",
    "Mink",
    "Giraffe",
    "Owl",
    "Crawdad",
    "Tiger",
    "Barracuda",
    "Parakeet",
    "Peafowl",
    "Marlin",
    "Gibbon",
    "Stoat",
    "Dove",
    "Python",
    "Firefly",
    "Gazelle",
    "Dinosaur",
    "Panther",
    "Cheetah",
    "Condor",
    "Partridge",
    "Mink",
    "Stork",
    "Turtle",
    "Roadrunner",
    "Hawk",
    "Albatross",
    "Kite",
    "Damselfly",
    "Bobcat",
    "Haddock",
    "Iguana",
    "Pheasant",
    "Mole",
    "Buzzard",
    "Koi",
  ];

  const generatedName = `${
    firstName[Math.floor(Math.random() * firstName.length)]
  } ${secondName[Math.floor(Math.random() * secondName.length)]}`;

  return generatedName;
};
